### ISSUE TITLE
assert_statsd_increment errors from 2.1.1 and above 

### ISSUE THREAD

**Issue by bheemreddy181** [Shopify/statsd-instrument#274]
We are using 2.0.12 version right once we moved to 2.1.1 version we started seeing errors as below 

``` No StatsD calls for metric app.portfolio.app.payment.rejected of type c were made.```

I could see there was change made on https://github.com/Shopify/statsd-instrument/pull/86 which is breaking Minitest:Assertions 

Sample block of code we used is 
```
it 'increments the rejected statsd counter' do
          assert_statsd_increment('app.portfolio.app.payment.rejected ', times: 1) do
            processor.call
      end
  end
```

The above assertion works fine on 2.0.12 and 2.1.0

**Comment by wvanbergen** [comment]
It's hard for me to know what is not working because I don't know what `processor.call` does.
Also, version2 is not actively being supported anymore now version 3.0 is out.

Does the issue persist on version 3.0? Can you provide a full snippet that demonstrate the problem?

**Comment by bheemreddy181** [comment]
Part of the processor.call is just doing `StatsD.increment` for the above event. I verified this on the latest version 3 as well getting same error.

**Comment by wvanbergen** [comment]
This example works fine for me:

``` ruby 
class MyTest < Minitest::Test
  include StatsD::Instrument::Assertions

  def test_increments_the_rejected_counter
    assert_statsd_increment('app.portfolio.app.payment.rejected', times: 1) do
      StatsD.increment('app.portfolio.app.payment.rejected')
    end
  end
end
```

I did remove a space character from your example, which I assume was not intentional.

**Comment by bheemreddy181** [comment]
Weird though - Is there any configuration changed from version 2 to version 3 ?

**Comment by wvanbergen** [comment]
Are you using a prefix for your metrics? I vaguely remember that you may have to be explicit about those in tests now.

**Comment by bheemreddy181** [comment]
After fixing the prefix issue i started seeing new errors now 

``` 
NameError:
       undefined local variable or method `pass' for #<RSpec::ExampleGroups::PaymentNotificationProcessor::Call::StatusErrored:0x00007faaddaff598>
     # /Users/user/.gem/ruby/2.5.7/gems/statsd-instrument-2.9.2/lib/statsd/instrument/assertions.rb:209:in `assert_statsd_expectations'
     # /Users/user/.gem/ruby/2.5.7/gems/statsd-instrument-2.9.2/lib/statsd/instrument/assertions.rb:76:in `assert_statsd_increment'
     # ./spec/interactors/payment_notification_processor_spec.rb:399:in `block (4 levels) in <top (required)>'
```

**Comment by wvanbergen** [comment]
`pass` is a standard method of minitest. (basically `assert true`). Based on your example, you're using RSpec, so that's likely the problem. This library comes with matchers as well that are more suitable for use in RSpec suites.

**Comment by bheemreddy181** [comment]
Does that mean I should be something like this 

```
 expect { StatsD.increment('app.portfolio.payment.rejected') }.to trigger_statsd_increment('counter')
```

rather than using the minitest assertions ?

**Comment by wvanbergen** [comment]
I have not used these matchers myself, but yes, something along those lines.

**Comment by wvanbergen** [comment]
For a quick fix you could also include a module like:
``` ruby
module Minitest::PassMethod
  def pass
    assert true
  end
end
```

**Comment by bheemreddy181** [comment]
Makes sense thanks
